### PR TITLE
Make random IDs suffix instead of prefix

### PR DESCRIPTION
**Pull request by eseliger**
Google has naming requirements that say "must start with a-z", which is not necessarily the case for the hex ids. This felt like the easiest fix to me.

### Test plan

Rolled out to dogfood.

### CODE REVIEW

**Review by sanderginn — APPROVED** [review]

**Review by michaellzc — COMMENTED** [review]
drive by comments.

I think people usually use a fixed prefix, append with a random string, then optionally add another suffix to identify the purpose of the resource (or you can put it before the random string)

we use `src` in cloud for most resources, short for `sourcegraph`. there are also people using `tf` to distinguish resources created with terraform from clickops.

**Comment by sanderginn** [comment]
I was just about to mention what @michaellzc pointed out, and also that `resource_prefix` is used in the random var, but is no longer actually a prefix this way, so might be a bit confusing

**Comment by eseliger** [comment]
> and also that resource_prefix is used in the random var, but is no longer actually a prefix this way, so might be a bit confusing

I don't think this is changed over previously if I understand right what you mean 🤔

**Comment by sanderginn** [comment]
Pushed changes that do the following:
* No longer generate the random ID with a prefix
* Instead always prepend the prefix to the resource name
* Add the random ID as a suffix

@michaellzc, @eseliger and I settled on this because it's a bit nicer to have the purpose of the resource (e.g. `docker-mirror`) before the random ID. For the end goal of randomizing resource names it doesn't make a difference.

**Review by michaellzc — APPROVED** [review]
lgtm

**Comment by eseliger** [comment]
LGTM, cannot approve :)

**Pull request merged**
